// 🚧 此檔案為自動產生，請勿手動修改
export const preloadImages = [
  "/images/character/aside_yy.png",
  "/images/character/aside_yy02.png",
  "/images/character/aside_yyBtn.png",
  "/images/character/bg.jpg",
  "/images/character/factions.png",
  "/images/character/factions1_nav1.jpg",
  "/images/character/factions1_nav2.jpg",
  "/images/character/factions1_nav3.jpg",
  "/images/character/factions1_nav4.jpg",
  "/images/character/factions1_role1_des.png",
  "/images/character/factions1_role2_des.png",
  "/images/character/factions1_role3_des.png",
  "/images/character/factions2_nav1.jpg",
  "/images/character/factions2_nav2.jpg",
  "/images/character/factions2_nav3.jpg",
  "/images/character/factions2_nav4.jpg",
  "/images/character/factions2_role1_des.png",
  "/images/character/factions2_role2_des.png",
  "/images/character/factions2_role3_des.png",
  "/images/character/factions2_role4_des.png",
  "/images/character/factionsBtn1.png",
  "/images/character/factionsBtn2.png",
  "/images/character/factionsNext.png",
  "/images/character/factionsPrev.png",
  "/images/character/手機板/factions1_m_poster3.jpg",
  "/images/character/手機板/factions1_m_poster4.jpg",
  "/images/character/手機板/factions1_role1_des.png",
  "/images/character/手機板/factions1_role2_des.png",
  "/images/character/手機板/factions1_role3_des.png",
  "/images/character/手機板/factions2_m_poster4.jpg",
  "/images/character/手機板/factions2_role1_des.png",
  "/images/character/手機板/factions2_role2_des.png",
  "/images/character/手機板/factions2_role3_des.png",
  "/images/character/手機板/factions2_role4_des.png",
  "/images/character/手機板/factionsBtn1.png",
  "/images/character/手機板/factionsBtn2.png",
  "/images/character/手機板/nte_mpic_anhunqu_20250514.jpg",
  "/images/character/手機板/nte_mpic_bohe_20250514.jpg",
  "/images/character/手機板/nte_mpic_fadiya_20250514.jpg",
  "/images/character/手機板/nte_mpic_nanali_20250514.jpg",
  "/images/character/手機板/nte_mpic_zaowu_20250514.jpg",
  "/images/character/手機板/pageArrow.png",
  "/images/character/手機板/pageRoleTit.png",
  "/images/city/bg.jpg",
  "/images/city/browser.png",
  "/images/city/citySlideNext.png",
  "/images/city/citySlideNum1.png",
  "/images/city/citySlideNum2.png",
  "/images/city/citySlideNum3.png",
  "/images/city/citySlideNum4.png",
  "/images/city/citySlideNum5.png",
  "/images/city/citySlideNum6.png",
  "/images/city/citySlidePrev.png",
  "/images/city/citySlideTit1.png",
  "/images/city/citySlideTit2.png",
  "/images/city/citySlideTit3.png",
  "/images/city/citySlideTit4.png",
  "/images/city/citySlideTit5.png",
  "/images/city/citySlideTit6.png",
  "/images/city/slide1 (1).jpg",
  "/images/city/slide2 (1).jpg",
  "/images/city/slide3 (1).jpg",
  "/images/city/slide4 (1).jpg",
  "/images/city/slide5 (1).jpg",
  "/images/city/slide6 (1).jpg",
  "/images/city/spray1.png",
  "/images/city/spray2.png",
  "/images/city/手機板/browser.png",
  "/images/city/手機板/citySlideNext.png",
  "/images/city/手機板/citySlideNum1.png",
  "/images/city/手機板/citySlideNum2.png",
  "/images/city/手機板/citySlideNum3.png",
  "/images/city/手機板/citySlideNum4.png",
  "/images/city/手機板/citySlideNum5.png",
  "/images/city/手機板/citySlideNum6.png",
  "/images/city/手機板/citySlidePrev.png",
  "/images/city/手機板/pageArrow.png",
  "/images/city/手機板/pageCityTit.png",
  "/images/city/手機板/slide1.jpg",
  "/images/city/手機板/slide2.jpg",
  "/images/city/手機板/slide3.jpg",
  "/images/city/手機板/slide4.jpg",
  "/images/city/手機板/slide5.jpg",
  "/images/city/手機板/slide6.jpg",
  "/images/city/手機板/spray1 (1).png",
  "/images/city/手機板/spray2 (1).png",
  "/images/footer/indexFoot.png",
  "/images/footer/indexFootNte.png",
  "/images/footer/indexFootWelcome.png",
  "/images/footer/Mobile/otherPlatform2.png",
  "/images/footer/otherPlatform.png",
  "/images/header/bgMusicSwitch.png",
  "/images/header/header.png",
  "/images/header/headerNav1.png",
  "/images/header/headerNav2.png",
  "/images/header/headerNav3.png",
  "/images/header/headerNav4.png",
  "/images/header/headerNav5.png",
  "/images/header/headerYYBtn.png",
  "/images/header/Mobile/header_menu.png",
  "/images/header/Mobile/header_yyBtn.png",
  "/images/header/Mobile/menu_bottom.png",
  "/images/header/NTE_logo.png",
  "/images/header/動畫群組01/city_shadow1.png",
  "/images/header/動畫群組01/city_shadow2.png",
  "/images/header/動畫群組01/city_shadow3.png",
  "/images/header/動畫群組01/city_shadow4.png",
  "/images/header/動畫群組02/shadow1.png",
  "/images/header/動畫群組02/shadow2.png",
  "/images/header/動畫群組02/shadow3.png",
  "/images/header/動畫群組02/shadow4.png",
  "/images/index/bg.jpg",
  "/images/index/go_ps_btn.png",
  "/images/index/indexVideoBtn.png",
  "/images/index/indexVideoPoster.jpg",
  "/images/index/indexYYBtn.png",
  "/images/index/手機板/indexYYBtn.png",
  "/images/index/手機板/pageArrow.png",
  "/images/index/手機板/pageArrow02.png",
  "/images/information/12.png",
  "/images/information/backIndex.png",
  "/images/information/bg.jpg",
  "/images/information/gamebroad.png",
  "/images/information/gameevent.png",
  "/images/information/gamenews.png",
  "/images/information/hotta_b.png",
  "/images/information/iwplay_world_b.png",
  "/images/information/listHeadNav.png",
  "/images/information/news.png",
  "/images/information/newsHead.png",
  "/images/information/newsMore.png",
  "/images/information/newsSwiper.png",
  "/images/information/nte250616_01.png",
  "/images/information/nte250616_02.jpeg",
  "/images/information/nte250616_03.png",
  "/images/information/手機板/newsHead.png",
  "/images/information/手機板/newsSwiper.png",
  "/images/information/手機板/nte250616_01.webp",
  "/images/information/手機板/nte250616_02.webp",
  "/images/information/手機板/nte250616_03.webp",
  "/images/information/手機板/pageArrow.png",
  "/images/load/bg.jpg",
  "/images/modal/popCont1_ZRRPZRBDRPTJKTTJ.png",
  "/images/modal/手機板/btn_Android_off.png",
  "/images/modal/手機板/btn_Android_on.png",
  "/images/modal/手機板/btn_ios_off.png",
  "/images/modal/手機板/btn_ios_on.png",
  "/images/modal/手機板/btn_pc_off.png",
  "/images/modal/手機板/btn_pc_on.png",
  "/images/modal/手機板/btn_ps_off.png",
  "/images/modal/手機板/btn_ps_on.png",
  "/images/modal/手機板/popClose.png",
  "/images/modal/手機板/popCont1_ZRRPZRBDRPTJKTTJ2.png",
  "/images/modal/手機板/popCont3.png",
  "/images/modal/手機板/pop_yy_form_tt.png",
  "/images/modal/手機板/pop_yy_privacy_tt.png",
  "/images/modal/手機板/yySubmit.png",
  "/images/news/02.webp",
  "/images/news/03.webp",
  "/images/news/04.webp",
  "/images/news/05.webp",
  "/images/news/06.webp",
  "/images/news/07.webp",
  "/images/news/08.webp",
  "/images/news/2025051618444747129861.webp",
  "/images/news/articleAside.png",
  "/images/news/articleBottom.png",
  "/images/news/articleHead.png",
  "/images/news/articlePage.jpg",
  "/images/news/articleTop.png",
  "/images/news/backNewsList.png",
  "/images/news/copyRightArrow.png",
  "/images/news/nte250616_01.png",
  "/images/news/nte250616_02.jpeg",
  "/images/news/nte250616_03.png",
  "/images/news/手機板/articleAside.png",
  "/images/news/手機板/articleBottom_m.png",
  "/images/news/手機板/articleHead_m.png",
  "/images/news/手機板/backNewsList_m.png",
  "/images/newsList/backIndex.png",
  "/images/newsList/bg.jpg",
  "/images/newsList/copyRightArrow.png",
  "/images/newsList/intelTit.png",
  "/images/newsList/listHeadNav.png",
  "/images/newsList/listItem.png",
  "/images/newsList/手機板/intelTit_m.png",
  "/images/newsList/版權區塊/12.png",
  "/images/newsList/版權區塊/hotta_b.png",
  "/images/newsList/版權區塊/iwplay_world_b.png",
  "/images/reserve/bg.jpg",
  "/images/reserve/eggBottom.png",
  "/images/reserve/eggPet.png",
  "/images/reserve/eggSlogan.png",
  "/images/reserve/pageEggshellYY.png",
  "/images/reserve/warningStrip.png",
  "/images/reserve/手機板/eggPet (1).png",
  "/images/reserve/手機板/eggSlogan.png",
  "/images/reserve/手機板/pageArrow.png",
  "/images/reserve/手機板/pageEggshellYY (1).png",
  "/images/world/01.png",
  "/images/world/02.png",
  "/images/world/03.png",
  "/images/world/04.png",
  "/images/world/bg.jpg",
  "/images/world/brand.png",
  "/images/world/brand02.png",
  "/images/world/brand1-1.jpg",
  "/images/world/brand1-2.jpg",
  "/images/world/brand2-1.jpg",
  "/images/world/brand2-2.jpg",
  "/images/world/brand2.png",
  "/images/world/brand3-1.jpg",
  "/images/world/brand3-2.jpg",
  "/images/world/brand4-1.jpg",
  "/images/world/brand4-2 (2).jpg",
  "/images/world/brand4-2.jpg",
  "/images/world/brandNext.png",
  "/images/world/brandPrev.png",
  "/images/world/green.png",
  "/images/world/guidepost.png",
  "/images/world/guidepost2.png",
  "/images/world/plate1.png",
  "/images/world/plate2.png",
  "/images/world/plate3.png",
  "/images/world/plate4.png",
  "/images/world/plateActive.png",
  "/images/world/plateTit1.png",
  "/images/world/plateTit2.png",
  "/images/world/plateTit3.png",
  "/images/world/plateTit4.png",
  "/images/world/red.png",
  "/images/world/trafficSign.png",
  "/images/world/trafficSign2.png",
  "/images/world/手機板/brand.png",
  "/images/world/手機板/brand02.png",
  "/images/world/手機板/brand03.png",
  "/images/world/手機板/brand04.png",
  "/images/world/手機板/brand1-1 (1).jpg",
  "/images/world/手機板/brand1-2 (1).jpg",
  "/images/world/手機板/brand2-1 (1).jpg",
  "/images/world/手機板/brand2-2 (1).jpg",
  "/images/world/手機板/brand3-1 (1).jpg",
  "/images/world/手機板/brand3-2 (1).jpg",
  "/images/world/手機板/brand4-1 (1).jpg",
  "/images/world/手機板/brand4-2 (1).jpg",
  "/images/world/手機板/guidepost.png",
  "/images/world/手機板/pageArrow.png",
  "/images/world/手機板/pageViewTit.png",
  "/images/world/手機板/plateLeft.png",
  "/images/world/手機板/plateRight.png",
  "/images/world/手機板/plateTit1 (1).png",
  "/images/world/手機板/plateTit2 (1).png",
  "/images/world/手機板/plateTit3 (1).png",
  "/images/world/手機板/plateTit4 (1).png",
  "/images/world/手機板/trafficSign.png"
];
